init:
  app: drlm
  sdk: go:1.13
  pass: ${env.PASS}
  pass-minio: ${env.PASS_MINIO}
  pass-core: ${env.PASS_CORE}
  docker-name: ${env.DOCKER_NAME}
  src: ${env.SRC}

pipeline:
  init:
    system:
      action: run
      request: "@system"
      tasks: "*"

    tls:
      wait-for-sshd:
        action: nop
        sleepTimeMs: 20000

      generate-certs:
        action: exec:run
        target:
          URL: ssh://${docker-name}-tls
          credentials: drlm
        commands:
          - rm -rf /tls/*
          - /usr/local/bin/generate-certs.sh
        env:
          ip_minio: ${docker-name}-minio
          ip_db: ${docker-name}-db
          ip_core: ${docker-name}-drlm-core

      stop:
        action: docker:stop
        name: ${docker-name}-tls

      restart-with-new-certs:
        stop:
          action: docker:stop
          names:
            - ${docker-name}-minio
              # - ${docker-name}-db
        start:
          action: docker:start
          names:
            - ${docker-name}-minio
              # - ${docker-name}-db

    datastore:
      action: run
      request: "@datastore"
      tasks: "*"

    app:
      action: run
      request: "@app"
      tasks: "*"

  destroy:
    system: run
    request: "@system"
    tasks: destroy
