tasks: $tasks
init:
  compose-file: docker/docker-compose.yml
  godev-target:
    URL: ssh://godev
    credentials: godev
pipeline:
  destroy:
    compose-down:
      action: docker/ssh:composeDown
      target: ${godev-target}
      source:
        URL: ${compose-file}

  init:
    build-images:
      drlmctl:
        action: docker:build
        path: docker/drlmctl
        tag:
          image: ${docker-name}-drlmctl
          version: latest
          
      tls:
        action: docker:build
        path: docker/tls
        tag:
          image: ${docker-name}-tls
          version: latest


    compose-up:
      action: docker/ssh:composeUp
      target: ${godev-target}
      source:
        URL: ${compose-file}
      runInBackground: true
